'use client'

import { useParams } from 'next/navigation'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { useLocale } from '@/components/LocaleContext'
import { notFound } from 'next/navigation'

// High-quality unsplash images per template
const heroImages: Record<string, { main: string; screen1: string; screen2: string; screen3: string; human: string }> = {
  'doktor-web-sitesi': {
    main: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1666214280391-8ff5bd3e0bf3?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
  },
  'kafe-mobil-uygulamasi': {
    main: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80',
  },
  'avukat-web-sitesi': {
    main: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1521791055366-0d553872952f?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&q=80',
  },
  'restoran-mobil-uygulamasi': {
    main: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=600&q=80',
  },
  'emlak-web-sitesi': {
    main: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
  },
  'spor-salonu-mobil-uygulamasi': {
    main: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
    screen1: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    screen2: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
    screen3: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&q=80',
    human: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80',
  },
}

// Mockup images generated by AI (fall back if not staged)
const mockupImages: Record<string, string> = {
  'doktor-web-sitesi': '/templates/doctor-web.jpg',
  'kafe-mobil-uygulamasi': '/templates/cafe-mobile.jpg',
  'avukat-web-sitesi': '/templates/lawyer-web.jpg',
}

export default function TemplateDetailPage() {
  const params = useParams()
  const slug = params?.slug as string
  const { t, locale } = useLocale()
  const data = t.pages.templates
  const item = data.items.find((i) => i.slug === slug)

  if (!item) return notFound()

  const imgs = heroImages[slug]

  return (
    <main className="min-h-screen bg-dark pt-28 pb-20">
      {/* ── Breadcrumb ───────────────────────────────────────── */}
      <div className="max-w-7xl mx-auto px-6 mb-8">
        <div className="flex items-center gap-2 text-white/40 text-sm">
          <Link href={`/${locale}`} className="hover:text-white transition-colors">
            {locale === 'ar' ? 'الرئيسية' : locale === 'en' ? 'Home' : 'Ana Sayfa'}
          </Link>
          <span>/</span>
          <Link href={`/${locale}/templates`} className="hover:text-white transition-colors">
            {data.badge}
          </Link>
          <span>/</span>
          <span className="text-white/70">{item.title}</span>
        </div>
      </div>

      {/* ── Hero Section ─────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-6 mb-20">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          {/* Text */}
          <motion.div initial={{ opacity: 0, x: -40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7 }}>
            <span
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-bold mb-6 text-white"
              style={{ background: item.color }}
            >
              {item.tag} · {item.sector}
            </span>
            <h1 className="text-4xl md:text-5xl font-display font-bold text-white leading-tight mb-6">
              {item.title}
            </h1>
            <p className="text-white/60 text-lg leading-relaxed mb-8">{item.heroDesc}</p>

            {/* Price + delivery */}
            <div className="flex items-center gap-8 mb-8 p-5 rounded-2xl glass border border-white/5">
              <div>
                <p className="text-white/40 text-xs mb-1">
                  {locale === 'ar' ? 'السعر' : locale === 'en' ? 'Price' : 'Fiyat'}
                </p>
                <p className="text-white text-2xl font-bold">₺{item.price}</p>
              </div>
              <div className="w-px h-10 bg-white/10" />
              <div>
                <p className="text-white/40 text-xs mb-1">
                  {locale === 'ar' ? 'وقت التسليم' : locale === 'en' ? 'Delivery' : 'Teslim Süresi'}
                </p>
                <p className="text-white font-semibold">{item.deliveryTime}</p>
              </div>
              <div className="w-px h-10 bg-white/10" />
              <div>
                <p className="text-white/40 text-xs mb-1">
                  {locale === 'ar' ? 'الدعم' : locale === 'en' ? 'Support' : 'Destek'}
                </p>
                <p className="text-white font-semibold">3 {locale === 'ar' ? 'أشهر' : locale === 'en' ? 'months' : 'ay'}</p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                href={`/${locale}/contact`}
                className="px-8 py-4 rounded-full text-sm font-bold text-dark text-center transition-all duration-300 hover:scale-105"
                style={{ background: `linear-gradient(135deg, ${item.color}, #7B2FBE)` }}
              >
                {locale === 'ar' ? 'احصل على عرض مجاني ←' : locale === 'en' ? 'Get Free Quote →' : 'Ücretsiz Teklif Al →'}
              </Link>
              <a
                href="https://wa.me/905522489971"
                target="_blank"
                rel="noopener noreferrer"
                className="px-8 py-4 rounded-full text-sm font-semibold text-white border border-[#25D366]/30 hover:border-[#25D366] hover:bg-[#25D366]/10 text-center transition-all duration-300"
              >
                {locale === 'ar' ? 'تواصل عبر واتساب' : locale === 'en' ? 'WhatsApp Us' : 'WhatsApp\'dan Yaz'}
              </a>
            </div>
          </motion.div>

          {/* Main image */}
          <motion.div
            initial={{ opacity: 0, x: 40, scale: 0.95 }}
            animate={{ opacity: 1, x: 0, scale: 1 }}
            transition={{ duration: 0.7 }}
            className="relative"
          >
            <div className="relative rounded-3xl overflow-hidden shadow-2xl border border-white/10">
              <img
                src={imgs.main}
                alt={item.title}
                className="w-full h-80 md:h-[420px] object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-tr from-dark/60 to-transparent" />
            </div>
            {/* Human badge */}
            <div className="absolute -bottom-6 -left-6 w-28 h-28 rounded-2xl overflow-hidden border-4 border-dark shadow-2xl">
              <img src={imgs.human} alt="professional" className="w-full h-full object-cover" />
            </div>

            {/* Floating badge */}
            <div className="absolute -top-4 -right-4 glass border border-white/10 rounded-2xl px-4 py-3 shadow-xl">
              <p className="text-xs text-white/40">{locale === 'ar' ? 'تسليم في' : locale === 'en' ? 'Delivery' : 'Teslim'}</p>
              <p className="text-white font-bold text-sm">{item.deliveryTime}</p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Screenshots Grid ─────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-6 mb-20">
        <h2 className="text-2xl font-bold text-white mb-8 text-center">
          {locale === 'ar' ? 'لقطات الشاشة' : locale === 'en' ? 'Screenshots' : 'Ekran Görüntüleri'}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[imgs.screen1, imgs.screen2, imgs.screen3].map((src, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="rounded-2xl overflow-hidden border border-white/5 hover:border-white/20 transition-all duration-300 group"
            >
              <img
                src={src}
                alt={`${item.title} screenshot ${i + 1}`}
                className="w-full h-52 object-cover group-hover:scale-105 transition-transform duration-500"
              />
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── Highlights ───────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-6 mb-20">
        <h2 className="text-3xl font-bold text-white mb-12 text-center">
          {locale === 'ar' ? 'أبرز المزايا' : locale === 'en' ? 'Key Features' : 'Öne Çıkan Özellikler'}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {item.highlights.map((h, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="flex gap-5 p-6 rounded-2xl bg-dark-card border border-white/5 hover:border-white/15 transition-all duration-300"
            >
              <span className="text-3xl flex-shrink-0">{h.icon}</span>
              <div>
                <h3 className="text-white font-semibold mb-1">{h.title}</h3>
                <p className="text-white/50 text-sm leading-relaxed">{h.text}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── Full Features List ───────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 mb-20">
        <div className="p-8 rounded-3xl border border-white/5 bg-dark-card">
          <h2 className="text-2xl font-bold text-white mb-6 text-center">
            {locale === 'ar' ? 'جميع المزايا المضمنة' : locale === 'en' ? 'All Included Features' : 'Dahil Olan Tüm Özellikler'}
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {item.features.map((f) => (
              <div key={f} className="flex items-center gap-3 text-white/70">
                <span
                  className="w-5 h-5 rounded-full flex-shrink-0 flex items-center justify-center"
                  style={{ background: `${item.color}25` }}
                >
                  <svg className="w-3 h-3" style={{ color: item.color }} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                </span>
                <span className="text-sm">{f}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Trust section (humans) ───────────────────────────── */}
      <section className="max-w-7xl mx-auto px-6 mb-20">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
          <div>
            <h2 className="text-3xl font-bold text-white mb-6">
              {locale === 'ar' ? 'لماذا تختار GlobalDijital؟' : locale === 'en' ? 'Why Choose GlobalDijital?' : 'Neden GlobalDijital?'}
            </h2>
            <div className="space-y-5">
              {[
                {
                  icon: '⚡',
                  t: locale === 'ar' ? 'تسليم سريع، جودة لا تُضاهى' : locale === 'en' ? 'Fast delivery, unmatched quality' : 'Hızlı teslim, üstün kalite',
                  d: locale === 'ar' ? 'مشاريع تُسلَّم في الموعد دائمًا مع ضمان الجودة الكاملة.' : locale === 'en' ? 'Projects always delivered on time with full quality guarantee.' : 'Projeler her zaman zamanında teslim edilir, tam kalite garantisi ile.',
                },
                {
                  icon: '🎯',
                  t: locale === 'ar' ? 'مخصص 100%' : locale === 'en' ? '100% Customizable' : '%100 Özelleştirilebilir',
                  d: locale === 'ar' ? 'كل قالب يُعدَّل ليناسب هوية علامتك تمامًا.' : locale === 'en' ? 'Every template is adapted to perfectly fit your brand identity.' : 'Her şablon markanıza mükemmel uyum sağlayacak şekilde özelleştirilir.',
                },
                {
                  icon: '🛡️',
                  t: locale === 'ar' ? 'دعم 3 أشهر مجاني' : locale === 'en' ? '3 months free support' : '3 ay ücretsiz destek',
                  d: locale === 'ar' ? 'بعد الإطلاق، نحن معك بشكل كامل لثلاثة أشهر.' : locale === 'en' ? 'After launch, we are fully with you for three months.' : 'Lansman sonrasında 3 ay boyunca tamamen yanınızdayız.',
                },
                {
                  icon: '🌍',
                  t: locale === 'ar' ? 'خبرة في 12 دولة' : locale === 'en' ? 'Experience in 12 countries' : '12 ülkede deneyim',
                  d: locale === 'ar' ? 'فريق عمل عالمي المستوى مع تجربة واسعة في مختلف القطاعات.' : locale === 'en' ? 'World-class team with vast experience across various sectors.' : 'Farklı sektörlerde geniş deneyime sahip dünya standartlarında ekip.',
                },
              ].map((item) => (
                <div key={item.t} className="flex gap-4 items-start">
                  <span className="text-2xl">{item.icon}</span>
                  <div>
                    <h3 className="text-white font-semibold">{item.t}</h3>
                    <p className="text-white/50 text-sm">{item.d}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="rounded-2xl overflow-hidden h-40 col-span-2">
              <img src={imgs.human} alt="professional team" className="w-full h-full object-cover object-top" />
            </div>
            <div className="rounded-2xl overflow-hidden h-36">
              <img src={imgs.screen1} alt="work sample" className="w-full h-full object-cover" />
            </div>
            <div className="rounded-2xl overflow-hidden h-36">
              <img src={imgs.screen2} alt="work sample" className="w-full h-full object-cover" />
            </div>
          </div>
        </div>
      </section>

      {/* ── Other templates ──────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-6">
        <h2 className="text-2xl font-bold text-white mb-8 text-center">
          {locale === 'ar' ? 'قوالب أخرى' : locale === 'en' ? 'Other Templates' : 'Diğer Şablonlar'}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {data.items
            .filter((i) => i.slug !== slug)
            .slice(0, 3)
            .map((i) => (
              <Link
                key={i.slug}
                href={`/${locale}/templates/${i.slug}`}
                className="group p-5 rounded-2xl border border-white/5 hover:border-white/20 bg-dark-card transition-all duration-300"
              >
                <span
                  className="inline-block px-3 py-1 rounded-full text-xs font-bold text-white mb-3"
                  style={{ background: i.color }}
                >
                  {i.tag}
                </span>
                <h3 className="text-white font-semibold group-hover:text-neon-blue transition-colors">{i.title}</h3>
                <p className="text-white/40 text-sm mt-1">₺{i.price} · {i.deliveryTime}</p>
              </Link>
            ))}
        </div>
      </section>
    </main>
  )
}
